# Generated by Django 3.2.2 on 2021-05-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='img/product_0_big.jpg', upload_to='img'),
        ),
    ]
