# Generated by Django 3.2.2 on 2021-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/product_0_big.jpg', upload_to='img'),
        ),
    ]
